name: Deploy Kana

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install --legacy-peer-deps
      - run: CI=false npm run build

      - run: touch build/.nojekyll

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - uses: actions/deploy-pages@v4
